# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "fsiem-terraform-ftn"
    encrypt = true
    key     = "devops_automation_tools/terraform.tfstate"
    region  = "us-east-1"
  }
}
