/*
  S3 buckets, there are two here:
  1. portal_bucket: Stores the static files of the portal UI. Terraform pulls
  the files from the build folder and uploads them as part of the deployment
  2. portal_log_bucket: Stores the logs generated by the cloudfront portal
*/


#
# fsiem-portal-api-${var.environment}
#

# Ignored as api gateway currently accesses this bucket publicly
#tfsec:ignore:aws-s3-block-public-acls tfsec:ignore:aws-s3-block-public-policy tfsec:ignore:aws-s3-ignore-public-acls tfsec:ignore:aws-s3-no-public-buckets
resource "aws_s3_bucket" "api_bucket" {
  bucket = "fsiem-portal-api-${var.environment}"
}

resource "aws_s3_bucket_versioning" "api_bucket" {
  bucket = aws_s3_bucket.api_bucket.id
  versioning_configuration {
    status = "Enabled"
  }
}

resource "aws_s3_bucket_server_side_encryption_configuration" "api_bucket" {
  bucket = aws_s3_bucket.api_bucket.id
  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "AES256"
    }
  }
}

resource "aws_s3_bucket_acl" "api_bucket" {
  bucket = aws_s3_bucket.api_bucket.id
  acl    = "private"
}

#
# fsiem-portal-ui-${var.environment}
#

# Ignored as cloudfront needs this bucket to be publicly accessible. Also cant be
# encrypted with KMS key as cloudfront cant access with it
#tfsec:ignore:aws-s3-block-public-acls tfsec:ignore:aws-s3-block-public-policy tfsec:ignore:aws-s3-ignore-public-acls tfsec:ignore:aws-s3-no-public-buckets tfsec:ignore:aws-s3-encryption-customer-key
resource "aws_s3_bucket" "portal_bucket" {
  bucket = "fsiem-portal-ui-${var.environment}"
}

resource "aws_s3_bucket_versioning" "portal_bucket" {
  bucket = aws_s3_bucket.portal_bucket.id
  versioning_configuration {
    status = "Enabled"
  }
}

resource "aws_s3_bucket_server_side_encryption_configuration" "portal_bucket" {
  bucket = aws_s3_bucket.portal_bucket.id
  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "AES256"
    }
  }
}

resource "aws_s3_bucket_acl" "portal_bucket" {
  bucket = aws_s3_bucket.portal_bucket.id
  acl    = "private"
}

#
# fsiem-portal-cloudfront-logs-${var.environment}
#

# Ignored as cloudfront needs to access this bucket publicly
#tfsec:ignore:aws-s3-block-public-acls tfsec:ignore:aws-s3-block-public-policy tfsec:ignore:aws-s3-ignore-public-acls tfsec:ignore:aws-s3-no-public-buckets
resource "aws_s3_bucket" "portal_log_bucket" {
  bucket = "fsiem-portal-cloudfront-logs-${var.environment}"
}

resource "aws_s3_bucket_server_side_encryption_configuration" "portal_log_bucket" {
  bucket = aws_s3_bucket.portal_log_bucket.id
  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "AES256"
    }
  }
}

resource "aws_s3_bucket_acl" "portal_log_bucket" {
  bucket = aws_s3_bucket.portal_log_bucket.id
  acl    = "private"
}

data "aws_iam_policy_document" "s3_policy" {
  statement {
    actions   = ["s3:GetObject"]
    resources = ["${aws_s3_bucket.portal_bucket.arn}/*"]

    principals {
      type        = "AWS"
      identifiers = [aws_cloudfront_origin_access_identity.access_identity.iam_arn]
    }
  }
}

resource "aws_s3_bucket_policy" "portal_bucket_policy" {
  bucket = aws_s3_bucket.portal_bucket.id
  policy = data.aws_iam_policy_document.s3_policy.json
}

module "template_files" {
  source   = "hashicorp/dir/template"
  version  = "~> 1.0.0"
  base_dir = var.portal_ui_build_path
}

resource "aws_s3_object" "dist" {
  for_each     = module.template_files.files
  bucket       = aws_s3_bucket.portal_bucket.id
  key          = each.key
  content_type = each.value.content_type

  # The template_files module guarantees that only one of these two attributes
  # will be set for each file, depending on whether it is an in-memory template
  # rendering result or a static file on disk.
  source  = each.value.source_path
  content = each.value.content

  # Unless the bucket has encryption enabled, the ETag of each object is an
  # MD5 hash of that object.
  etag = each.value.digests.md5
}
