apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: summer-trip
  name: summer-trip-deployment
  annotations:
    link.argocd.argoproj.io/external-link: https://hub.docker.com/repository/docker/chauwei150/summer-trip
spec:
spec:
  replicas: 1
  selector:
    matchLabels:
      app: summer-trip
  template:
    metadata:
      labels:
        app: summer-trip
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: summer-trip-deployment
        image: chauwei150/summer-trip:v1
        imagePullPolicy: Always
