apiVersion: v1
kind: Service
metadata:
  name: hello-app-service
spec:
  selector:
    app: hello
  ports:
  - name: http
    nodePort: 31732
    port: 80
    protocol: TCP
    targetPort: 8080
  type: NodePort
