<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <AWSProjectType>Lambda</AWSProjectType>
    <!--
      The following is against convention, where we have a different Assembly Name than the project name.
      Setting this to `bootstrap` allows us to run a custom runtime for .net when we deploy to lambda.
      As of AUG 2021
      .net 5, is not an LTS version, and
      .net 3.1 is too old and
      .net 6 is just in preview
      Once .net 6 is in GA, we can move to that and utilise the runtime on lambda
      If we do not set this value, the bootstrap runnner on Lambda does not work
    -->
    <AssemblyName>bootstrap</AssemblyName>
    <RootNamespace>FinsProvisioning</RootNamespace>
    <UserSecretsId>451c4403-4066-49c5-9376-a580c3f7e389</UserSecretsId>
  </PropertyGroup>
  <PropertyGroup>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(RunConfiguration)' == 'IIS Development' " />
  <PropertyGroup Condition=" '$(RunConfiguration)' == 'IIS Production' " />
  <PropertyGroup Condition=" '$(RunConfiguration)' == 'IIS DevProduction' " />
  <ItemGroup>
    <Compile Remove="AwsExtensions\Models\**" />
    <Content Remove="AwsExtensions\Models\**" />
    <EmbeddedResource Remove="AwsExtensions\Models\**" />
    <None Remove="AwsExtensions\Models\**" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Amazon.AspNetCore.Identity.Cognito" Version="3.0.2" />
    <PackageReference Include="Amazon.Lambda.RuntimeSupport" Version="1.10.0" />
    <PackageReference Include="AWSSDK.CertificateManager" Version="3.7.300.78" />
    <PackageReference Include="AWSSDK.CloudFormation" Version="3.7.307.4" />
    <PackageReference Include="AWSSDK.CognitoIdentityProvider" Version="3.7.303.23" />
    <PackageReference Include="AWSSDK.EC2" Version="3.7.323.2" />
    <PackageReference Include="AWSSDK.EventBridge" Version="3.7.302.44" />
    <PackageReference Include="AWSSDK.SecretsManager" Version="3.7.302.53" />
    <PackageReference Include="AWSSDK.S3" Version="3.7.307.19" />
    <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="3.7.300" />
    <PackageReference Include="AWSSDK.DynamoDBv2" Version="3.7.302.19" />
    <PackageReference Include="Amazon.Lambda.AspNetCoreServer" Version="9.0.0" />
    <PackageReference Include="AWSSDK.SimpleSystemsManagement" Version="3.7.303.27" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.4" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="8.0.4" />
    <PackageReference Include="AWSSDK.Core" Version="3.7.303.18" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\FortinetOne.Client\FortinetOne.Client.csproj" />
    <ProjectReference Include="..\FortiMonitor.Client\FortiMonitor.Client.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <None Remove="AWSSDK.Core" />
  </ItemGroup>
</Project>
