export enum Progress {
    EMPTY = '',
    CREATE_COMPLETE = 'CREATE_COMPLETE',
    UPDATE_IN_PROGRESS = 'UPDATE_IN_PROGRESS',
    UPDATE_COMPLETE = 'UPDATE_COMPLETE',
    CREATE_FAILED = 'CREATE_FAILED',
    CREATE_IN_PROGRESS = 'CREATE_IN_PROGRESS',
    DELETE_IN_PROGRESS = 'DELETE_IN_PROGRESS',
    DELETE_COMPLETE = 'DELETE_COMPLETE',
    DELETE_FAILED = 'DELETE_FAILED'
}
