apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: summer-trip
  name: summer-trip-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: summer-trip
  template:
    metadata:
      labels:
        app: summer-trip
    spec:
      imagePullSecrets:      
      - name: regcred
      containers:
      - name: summer-trip
        image: 730118560661.dkr.ecr.us-east-1.amazonaws.com/summer-trip:latest
        imagePullPolicy: Always
