version: "3.9"
# Manually create default network to avoid issues with FortiClient VPN.
# From: https://stackoverflow.com/a/50948930/706456
networks:
  default:
    ipam:
      config:
        - subnet: 172.16.236.0/24
          gateway: 172.16.236.1
services:
  portal_api_build:
    build:
      context: ./
      dockerfile: build.dockerfile
      args:
        # Assign the values of env variables to the args
        # This is required for accessing env vars at build time
        VERSION_MAJOR: $VERSION_MAJOR
        VERSION_MINOR: $VERSION_MINOR
        VERSION_PATCH: $VERSION_PATCH
        VERSION_REVISION: $VERSION_REVISION
        DEVOPS_BUILD_NUMBER: $DEVOPS_BUILD_NUMBER
        DEVOPS_BUILD_TYPE: $DEVOPS_BUILD_TYPE
        DOCKER_REGISTRY: ${DOCKER_REGISTRY_NEXUS_URL:-mcr.microsoft.com/}
        DOCKER_DOTNET_VERSION: ${DOCKER_DOTNET_VERSION}
        NEXUS_NUGET_PROXY: ${NEXUS_NUGET_PROXY:-https://dops-jfrog.fortinet-us.com/artifactory/api/nuget/v3/nuget-group/index.json}
        NEXUS_APK_PROXY: ${NEXUS_APK_PROXY:-https://dops-jfrog.fortinet-us.com/artifactory/alpine-remote/v3.19/main}
        NEXUS_APK_COMMUNITY_PROXY: ${NEXUS_APK_COMMUNITY_PROXY:-https://dops-jfrog.fortinet-us.com/artifactory/alpine-remote/v3.19/community}
    image: ${DOCKER_REGISTRY_NEXUS_URL}portal_api_build
    container_name: portal_api_build
