version: "3.9"
services:
  # We can only use mounted volumes at the top level of contaner, we cannot mount a volume
  # when using docker-in-a-docker. Because our build action runs using
  # "gitlab ci container > build container > api container", the last "api container"
  # cannot mount file system from the "build container". This is why update action runs
  # like this: "gitlab ci container > api update container", where we can mount volume
  # with our source code.
  portal_ui_build:
    volumes:
      # NOTE: this needs to be different to the main docker-compose.yaml
      # Otherwise updates don't work.
      - ./:/node/portal_ui_build
    working_dir: /node/portal_ui_build
